---
- name: Provision idm machine
  ansible.builtin.include_tasks: create_idm_ec2.yml

- name: Provision satellite machine
  ansible.builtin.include_tasks: create_sat_ec2.yml

- name: Provision aap machine
  ansible.builtin.include_tasks: create_aap_ec2.yml

- name: Provision hub machine
  ansible.builtin.include_tasks: create_hub_ec2.yml
